### ISSUE TITLE
Wrong default scalers

### ISSUE THREAD

**Issue by HekpoMaH** [lukecavabarrett/pna#1]
Hi all! First of all, great paper, I could definitely see it boosting GNN research.

I believe there is an issue with the default parameters in `models/pna/train.py`, line 11, namely:
```
parser.add_argument('--scalers', type=str, default='identity exp log', help='Scalers to use')
```

`exp` and `log` are not part of the scalers. Based on the paper (and the README) I assume you mean `amplification` and `attenuation`. Currently, as the code is, not providing scalers argument results in a `KeyError`.

Thanks!

**Comment by gcorso** [comment]
Hi, thank you for the comment. Yes sorry, we left the old names in the default parameters, indeed, it should be `amplification` and `attenuation`! I will change the code right away.

Thank you very much again for pointing it out!
