### ISSUE TITLE
Potential error with average degrees in example.py

### ISSUE THREAD

**Issue by gpdwatkins** [lukecavabarrett/pna#12]
I think the calculation of average degrees contains an error when `example.py` is called.

The `deg` variable (defined in `pna/models/pytorch_geometric/example.py`) contains, at index `i`, the number of vertices in the dataset with degree `i`. This is passed to the `init` function of `PNAConvSimple` (in `pna/models/pytorch_geometric/pna.py`) to calculate the values for `self.avg_deg`.

But we end up calculating the average of the degree **counts**, not the average of the degrees. The following two (non-optimised) solutions would work:

* Edit `example.py` so deg is actually a list of degrees
```
deg = []
for data in dataset[split_idx['train']]:
    d = degree(data.edge_index[1], num_nodes=data.num_nodes, dtype=torch.long)
    deg += list(d)
deg = torch.tensor(deg, dtype=torch.long)
```
* Edit `pna.py` to handle binned frequency tensors (such as is returned by `torch.bincount`)
```
total_no_vertices = deg.sum()
bin_degrees = torch.arange(len(deg))
self.avg_deg: Dict[str, float] = {
    'lin': ((bin_degrees*deg).sum()/total_no_vertices).item(),
    'log': (((bin_degrees+1).log()*deg).sum()/total_no_vertices).item(),
    'exp': ((bin_degrees.exp()*deg).sum()/total_no_vertices).item(),
}
```
Apologies if I've misunderstood what the `avg_deg` variable is supposed to contain. Note I haven't checked elsewhere to see if this same issue arises in other files.

**Comment by gcorso** [comment]
Hi @gpdwatkins, thank you very much for spotting this bug in the PyTorch Geometric implementation (unfortunately this was done after the project so I admit that we did not test it thoroughly). I like the second solution, I'll push the change to the repo and add you to the credits.
Btw it would be great to also fix this in the PyTorch Geometric implementation of PNA, would you like to raise a pull request on that repo?

**Comment by gpdwatkins** [comment]
@gcorso thanks very much for adding me to the credits! Yes, I'd be happy to raise a pull request on the PyTorch Geometric repo with these changes.
Cheers!

**Comment by gcorso** [comment]
Thank you!

**Comment by gpdwatkins** [comment]
My pleasure. I thought this was a really nice paper by the way - I had an intuition that something was being lost in the aggregation of messages and the paper presents the issue really clearly with a nice solution. That certainly can't be said of every paper I read!!!
