### ISSUE TITLE
The use of the pytorch code

### ISSUE THREAD

**Issue by yangyang117** [lukecavabarrett/pna#13]
Hi, thank you very much for your sharing of your code. Is there any way that in which kind of code, you can provide a examples how to create the input  and how to use the layer?

**Comment by gcorso** [comment]
Hi, 
For the DGL version of the code you can look at all of our experiments and the [docs of DGL](https://github.com/lukecavabarrett/pna/blob/master/models/pytorch_geometric/example.py) for a much simpler one. For PyTorch Geometric you can find [here](https://github.com/lukecavabarrett/pna/blob/master/models/pytorch_geometric/example.py) a relatively simple example.
I hope this helps!
