### ISSUE TITLE
Bug in argparse

### ISSUE THREAD

**Issue by zq0x7a0x71** [lukecavabarrett/pna#7]
It seems that `args.divide_input_first` and `args.divide_input_first` will always be True, even if we set `--divide_input_first=False` in the command line.  A similar question can be found [here](https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse).

**Comment by gcorso** [comment]
Thanks for noticing, it should be fixed now!

**Comment by zq0x7a0x71** [comment]
Hi, @gcorso. Thanks for your reply. 

Do we need to modify the running script as well? If we can use the previous script to reproduce the results, then both  `args.divide_input_first` and `args.divide_input_first` should be True. However, using the current script will set them to be False sometimes. The results may be different from previous ones.

**Comment by gcorso** [comment]
Yes, I believe so. I'll also check that the results & parameters correspond as soon as I have some spare time. Thanks
